"""
Python script written to combine the images generated by the
[squaremap](https://modrinth.com/plugin/squaremap) Minecraft plugin into one map.
Not affiliated with squaremap or its authors.

See the [GitHub page](https://github.com/svioletg/py-squaremap-combiner) for more detailed usage information.
"""
